---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: l2-network-{{.Iteration}}
spec:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: [ "cudn-density-l2-noPods-{{.Iteration}}" ]
  network:
    topology: Layer2
    layer2:
        role: Primary
        subnets: ["10.132.0.0/16"]